name: Auto Extract ZIP

on:
  push:
    paths:
      - '*.zip'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Extract ZIP
      run: |
        unzip -o '*.zip'
        rm '*.zip'
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-extract ZIP"
        git push
